name: Build Tauri App with Cargo

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: Build Tauri App
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest]

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: List all files
        run: ls -a
